@isTest
public class TestInfermedica {
    
    @isTest    
    public static void TestSendQuery () {
        
        InfermedicaQuery query = new InfermedicaQuery();
        
        query.s_1558 = true;
        query.s_299 = true;
        query.s_1293 = true;
        query.s_13 = true;
        query.s_1802 = true;
        query.s_1848 = true;
        query.s_1860 = true;
        query.s_1557 = true;
        query.s_1387 = true;
        query.s_1207 = true;
        query.s_15 = true;
        query.s_1202 = true;
        query.s_14 = true;
        query.s_1844 = true;
        query.s_1852 = true;
        query.s_1853 = true;
        query.s_1840 = true;
        query.s_1842 = true;
        query.s_1729 = true;
        query.s_1854 = true;
        query.s_1591 = true;
        query.s_1851 = true;
        query.s_1782 = true;
        query.s_1783 = true;
        query.s_1598 = true;
        query.s_1532 = true;
        query.s_16 = true;
        query.s_17 = true;
        query.s_1845 = true;
        query.s_1846 = true;
        query.s_471 = true;
        query.s_1847 = true;
        query.s_57 = true;
        query.s_1531 = true;
        query.s_1855 = true;
        query.s_1528 = true;
        query.s_1195 = true;
        query.s_1369 = true;
        query.s_1843 = true;
        query.s_1929 = true;
        query.s_1514 = true;
        query.s_1589 = true;
        query.s_1392 = true;
        query.s_1400 = true;
        query.s_1190 = true;
        query.s_159 = true;
        query.s_1206 = true;
        query.s_1205 = true;
        query.s_53 = true;
        query.s_1339 = true;
        query.s_38 = true;
        query.s_663 = true;
        query.s_1189 = true;
        query.s_1192 = true;
        query.s_1198 = true;
        query.s_1772 = true;
        query.s_50 = true;
        query.s_31 = true;
        query.s_51 = true;
        query.s_35 = true;
        query.s_1763 = true;
        query.s_42 = true;
        query.s_30 = true;
        query.s_1204 = true;
        query.s_46 = true;
        query.s_1925 = true;
        query.s_37 = true;
        query.s_1490 = true;
        query.s_1489 = true;
        query.s_36 = true;
        query.s_1952 = true;
        query.s_1197 = true;
        query.s_1601 = true;
        query.s_48 = true;
        query.s_1509 = true;
        query.s_1200 = true;
        query.s_45 = true;
        query.s_1178 = true;
        query.s_1580 = true;
        query.s_105 = true;
        query.s_103 = true;
        query.s_106 = true;
        query.s_1858 = true;
        query.s_1924 = true;
        query.s_104 = true;
        query.s_662 = true;
        query.s_670 = true;
        query.s_526 = true;
        query.s_8 = true;
        query.s_412 = true;
        query.s_1850 = true;
        query.s_1849 = true;
        query.s_1121 = true;
        query.s_1979 = true;
        query.s_1376 = true;
        query.s_305 = true;
        query.s_1949 = true;
        query.s_307 = true;
        query.s_1365 = true;
        query.s_801 = true;
        query.s_21 = true;
        query.s_1870 = true;
        query.s_1868 = true;
        query.s_1901 = true;
        query.s_1907 = true;
        query.s_1535 = true;
        query.s_1762 = true;
        query.s_625 = true;
        query.s_799 = true;
        query.s_1349 = true;
        query.s_24 = true;
        query.s_604 = true;
        query.s_1780 = true;
        query.s_1781 = true;
        query.s_970 = true;
        query.s_23 = true;
        query.s_25 = true;
        query.s_1912 = true;
        query.s_605 = true;
        query.s_1193 = true;
        query.s_1905 = true;
        query.s_22 = true;
        query.s_1864 = true;
        
        query.sendMyRequest();
        
        System.assertNotEquals(true, query.s_1864);
        
    }
    
    
    
}